src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $Note = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Commentaire = null;

    #[ORM\Column]
    private ?bool $Is_Valid = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Jeux $Jeux = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    private ?Utilisateurs $Utilisateurs = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->Note;
    }

    public function setNote(?int $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->Commentaire;
    }

    public function setCommentaire(string $Commentaire): self
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }

    public function isIsValid(): ?bool
    {
        return $this->Is_Valid;
    }

    public function setIsValid(bool $Is_Valid): self
    {
        $this->Is_Valid = $Is_Valid;

        return $this;
    }

    public function getJeux(): ?Jeux
    {
        return $this->Jeux;
    }

    public function setJeux(?Jeux $Jeux): self
    {
        $this->Jeux = $Jeux;

        return $this;
    }

    public function getUtilisateurs(): ?Utilisateurs
    {
        return $this->Utilisateurs;
    }

    public function setUtilisateurs(?Utilisateurs $Utilisateurs): self
    {
        $this->Utilisateurs = $Utilisateurs;

        return $this;
    }
}

src/Entity/Jeux.php
<?php

namespace App\Entity;

use App\Repository\JeuxRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JeuxRepository::class)]
class Jeux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 500)]
    private ?string $Url = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Image = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 2, scale: 1, nullable: true)]
    private ?string $Note = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $Date_sortie = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'jeuxes')]
    private Collection $Genre;

    #[ORM\OneToMany(mappedBy: 'Jeux', targetEntity: Avis::class)]
    private Collection $avis;

    public function __construct()
    {
        $this->Genre = new ArrayCollection();
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->Url;
    }

    public function setUrl(string $Url): self
    {
        $this->Url = $Url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->Note;
    }

    public function setNote(?string $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeImmutable
    {
        return $this->Date_sortie;
    }

    public function setDateSortie(\DateTimeImmutable $Date_sortie): self
    {
        $this->Date_sortie = $Date_sortie;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenre(): Collection
    {
        return $this->Genre;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->Genre->contains($genre)) {
            $this->Genre->add($genre);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->Genre->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setJeux($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getJeux() === $this) {
                $avi->setJeux(null);
            }
        }

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\JeuxRepository;

class AccueilController extends AbstractController
{
    #[Route('/accueil', name: 'app_accueil')]
    public function index(JeuxRepository $JeuxRepository): Response
    {
        $LastJeux = $JeuxRepository->findLastJeux();
        return $this->render('accueil/index.html.twig', [
            'LastJeux' => $LastJeux,
        ]);
    }
}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AccueilController!{% endblock %}
      

{% block body %}
{% include "header.html.twig" %}

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Game_2F</h1>
        <p class="lead text-muted">Bienvenue sur notre site Game_2F afin de vous renseigner sur les diifèrentes sorties des jeux vidéos sur les " dernières décennie</p>
        <p>
          <a href="#" class="btn btn-primary my-2">S'inscrire</a>
          <a href="#" class="btn btn-secondary my-2">Se connecter</a>
        </p>
      </div>
    </div>
  </section>

    <div class="container mt-5">
            <div class="row row-cols-1 row-cols-md-3 g-5 justify-content-center">
            {% for LastJeu in LastJeux %}
                <div class="col">
                <div class="card h-100 d-flex" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
                    <img src="{{ '/' ~ LastJeu.image }}" style="height: 380px;"  alt="{{ LastJeu.title }}">
                    <div class="card-body">
                    <h5 class="card-title">{{ LastJeu.title }}</h5>
                    <p class="card-text">Note : {{ LastJeu.note }}/5</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
                </div>
            {% endfor %}
            </div>
        </div>
      {% include "footer.html.twig" %}
{% endblock %}